[PRODUCTION]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    EMAIL_ACCOUNT_PATH = '/var/mail/vhosts/'

[TESTING]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    EMAIL_ACCOUNT_PATH = '/tmp/mail/vhost/'

[DEVELOPMENT]
    SECRET_KEY = 'change_me'
    PASSWORD_HASH = 'change_me'
    EMAIL_ACCOUNT_PATH = '/tmp/mail/vhost/'
